### DISCUSSION TITLE
nginx client_max_body_size

### DISCUSSION THREAD

**Discussion by IvayloAtanasov** [akash-network/community#482] [Q&A] [answered]
Hello Akash community

I'm running a node container in a leased Akash provider instance, but I need to change the default client_max_body_size of the nginx instance that wraps my container. Is this possible?

I can't do it from inside the container and was only able to find [these settings](https://github.com/akash-network/docs/blob/master/sdl/README.md#servicesexpose) which seem related to nginx, but none of them allow me to alter the default configuration files. This is a real blocker for me, since I need to temporarily store files, often large than the default 1Mb limit.

**Comment by zJuuu** [comment, marked as answer]
Hey, check out this example to change the http settings: https://docs.akash.network/other-resources/experimental/akash-deployments-via-terraform/akash-sdl-hello-world-example#hello-world-sdl

**Reply by IvayloAtanasov** [reply]
Hey, thank you for the quick response.

I've tried this setting but unfortunately it didn't make a difference. This is roughly what I have in my SDL

```
  app:
    image: node:20.10.0
    env:
      - 'url=https://my.url'

    command:
      - "sh"
      - "-c"
    args:
      - 'npm start'

    expose:
      - port: 7000
        as: 80
        http_options:
          max_body_size: 104857600
        accept:
          - "my.url"
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
```
