### ISSUE TITLE
[Provider Audit]: provider.akash-cloud.com

### ISSUE THREAD

**Issue by birchcoin** [akash-network/community#493]
### 1. Make sure your provider has community provider attributes:

```
node1:~$ provider-services query provider get akash1<redacted> -o text
attributes:
- key: region
  value: us-east
- key: host
  value: akash
- key: tier
  value: community
- key: organization
  value: akash-cloud.com
- key: statusPage
  value: status.akash-cloud.com
- key: hardwareCpuArch
  value: x64
- key: hardwareGpuVendor
  value: Nvidia
- key: featPersistentStorageType
  value: beta1
- key: capabilities/storage/1/class
  value: beta1
- key: capabilities/storage/1/persistent
  value: "true"
- key: capabilities/gpu/vendor/nvidia/model/tu117
  value: "true"
host_uri: https://provider.akash-cloud.com:8443

```

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
ubuntu:~$ host anything.ingress.akash-cloud.com
anything.ingress.akash-cloud.com has address 71.65.232.20

```

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
Confirmed

# Audit Steps:

## Leave contact information (optional)
1. Name
Pete
2. Discord handle or Telegram handle
bigdahog
3. Contact email address
postmaster@akash-cloud.com
