### ISSUE TITLE
[Provider Audit] provider.us.kloudmos.com

### ISSUE THREAD

**Issue by nathandiruggiero** [akash-network/community#693]
Name : Chiroxo
Discord : Chiroxo
Contact email : contact.kloudmos@gmail.com

**Comment by andy108369** [comment]
checking with Chiroxo whether his provider is ready to be reviewed & audited.

```
$ provider_info2.sh provider.us.kloudmos.com
PROVIDER INFO
BALANCE: 49.035943
"hostname"                  "address"
"provider.us.kloudmos.com"  "akash1u6dq9l8rfzyw3gdm9s05w0hzqr9w5lzlj53gq6"

Total/Available/Used (t/a/u) per node:
"name"                      "cpu(t/a/u)"     "gpu(t/a/u)"  "mem(t/a/u GiB)"   "ephemeral(t/a/u GiB)"
"provider.us.kloudmos.com"  "8/4.725/3.275"  "0/0/0"       "23.47/19.67/3.8"  "1119.22/1118.72/0.5"

ACTIVE TOTAL:
"cpu(cores)"  "gpu"  "mem(GiB)"  "ephemeral(GiB)"  "beta1(GiB)"  "beta2(GiB)"  "beta3(GiB)"
0.1           0      0.5         0.5               0             0             0

PERSISTENT STORAGE:
"storage class"  "available space(GiB)"

PENDING TOTAL:
"cpu(cores)"  "gpu"  "mem(GiB)"  "ephemeral(GiB)"  "beta1(GiB)"  "beta2(GiB)"  "beta3(GiB)"
```

```
$ provider-services query provider get akash1u6dq9l8rfzyw3gdm9s05w0hzqr9w5lzlj53gq6 -o text
attributes:
- key: host
  value: akash
- key: tier
  value: community
- key: organization
  value: kloudmos
- key: cpu
  value: amd
- key: country
  value: US
- key: city
  value: Seattle
- key: region
  value: Washington
- key: timezone
  value: UTC-7
- key: arch
  value: x86_64
- key: network-speed-up
  value: "500"
- key: network-speed-down
  value: "1000"
- key: status-page
  value: https://stats.uptimerobot.com/jKppMSYv2R
host_uri: https://provider.us.kloudmos.com:8443
info:
  email: contact.kloudmos@gmail.com
  website: under_construction
owner: akash1u6dq9l8rfzyw3gdm9s05w0hzqr9w5lzlj53gq6
```

**Comment by nathandiruggiero** [comment]
Provider ready to be reviewed and audited

**Comment by vigneshv-ocl** [comment]
Hi @nathandiruggiero , Welcome to Akash!!
```
provider-services query provider get akash1u6dq9l8rfzyw3gdm9s05w0hzqr9w5lzlj53gq6
attributes:
- key: host
  value: akash
- key: tier
  value: community
- key: organization
  value: kloudmos
- key: cpu
  value: amd
- key: country
  value: US
- key: city
  value: Seattle
- key: region
  value: Washington
- key: timezone
  value: UTC-7
- key: arch
  value: x86_64
- key: network-speed-up
  value: "500"
- key: network-speed-down
  value: "1000"
- key: status-page
  value: https://stats.uptimerobot.com/jKppMSYv2R
host_uri: https://provider.us.kloudmos.com:8443
info:
  email: contact.kloudmos@gmail.com
  website: under_construction
owner: akash1u6dq9l8rfzyw3gdm9s05w0hzqr9w5lzlj53gq6
```
Provider is signed
```
provider-services query audit get akash1u6dq9l8rfzyw3gdm9s05w0hzqr9w5lzlj53gq6
pagination: null
providers:
- attributes:
  - key: arch
    value: x86_64
  - key: city
    value: Seattle
  - key: country
    value: US
  - key: cpu
    value: amd
  - key: host
    value: akash
  - key: network-speed-down
    value: "1000"
  - key: network-speed-up
    value: "500"
  - key: organization
    value: kloudmos
  - key: region
    value: Washington
  - key: status-page
    value: https://stats.uptimerobot.com/jKppMSYv2R
  - key: tier
    value: community
  - key: timezone
    value: UTC-7
  auditor: akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
  owner: akash1u6dq9l8rfzyw3gdm9s05w0hzqr9w5lzlj53gq6
```
