### ISSUE TITLE
[Provider Audit] provider.de.kloudmos.com

### ISSUE THREAD

**Issue by nathandiruggiero** [akash-network/community#694]
Name : Chiroxo
Discord : Chiroxo
Contact email : contact.kloudmos@gmail.com

**Comment by nathandiruggiero** [comment]
> ~duplicate of #693~ Upd: figured this one is `.de.` and the other one is `.us.`

Yep, ready to be audited and reviewed

**Comment by vigneshv-ocl** [comment]
Hi @nathandiruggiero , Welcome to Akash!!
```
provider-services query provider get akash167hmrx0x2guklnnqrqedgdstj0usfzhgxkn5pj -o text
attributes:
- key: host
  value: akash
- key: tier
  value: community
- key: organization
  value: kloudmos
- key: cpu
  value: amd
- key: country
  value: DE
- key: city
  value: Dusseldorf
- key: region
  value: North Rhine-Westphalia
- key: timezone
  value: utc+2
- key: arch
  value: x86_64
- key: network-speed-up
  value: "500"
- key: network-speed-down
  value: "1000"
- key: status-page
  value: https://stats.uptimerobot.com/jKppMSYv2R
host_uri: https://provider.de.kloudmos.com:8443
info:
  email: contact.kloudmos@gmail.com
  website: under_construction
owner: akash167hmrx0x2guklnnqrqedgdstj0usfzhgxkn5pj
```

Provider is signed
```
provider-services query audit get akash167hmrx0x2guklnnqrqedgdstj0usfzhgxkn5pj
pagination: null
providers:
- attributes:
  - key: arch
    value: x86_64
  - key: city
    value: Dusseldorf
  - key: country
    value: DE
  - key: cpu
    value: amd
  - key: host
    value: akash
  - key: network-speed-down
    value: "1000"
  - key: network-speed-up
    value: "500"
  - key: organization
    value: kloudmos
  - key: region
    value: North Rhine-Westphalia
  - key: status-page
    value: https://stats.uptimerobot.com/jKppMSYv2R
  - key: tier
    value: community
  - key: timezone
    value: utc+2
  auditor: akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
  owner: akash167hmrx0x2guklnnqrqedgdstj0usfzhgxkn5p
```

you can find it here as well 👇 
<img width="1187" alt="image" src="https://github.com/user-attachments/assets/2dc8eb02-1318-4870-969e-ed40b3c0f196">
