### ISSUE TITLE
[Provider Audit] provider.alexpedersen.dev

### ISSUE THREAD

**Issue by alexx855** [akash-network/community#703]
### 1. Make sure your provider has community provider attributes and your contact details (email, website) ✅

```yaml
attributes:
    - key: organization
      value: Alex Pedersen
    - key: tier
      value: community
    - key: host
      value: akash
email: provider@alexpedersen.dev
website: alexpedersen.dev
```

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP) ✅
```
host test.ingress.alexpedersen.dev
```

## Leave contact information 
1. Name: Alex Pedersen
2. Discord handle: alexx855.eth
3. Contact email address: provider@alexpedersen.dev

**Comment by vigneshv-ocl** [comment]
could you please load up more AKT. i see the balance is very less. ideally 20-50AKT should be good

```
./provider_info2.sh provider.alexpedersen.dev
PROVIDER INFO
BALANCE: 3.739558
"hostname"                   "address"
"provider.alexpedersen.dev"  "akash196z5qcz3m5suaymz653hcjzlwe5zhq25vnhj0f"

Total/Available/Used (t/a/u) per node:
"name"   "cpu(t/a/u)"  "gpu(t/a/u)"  "mem(t/a/u GiB)"  "ephemeral(t/a/u GiB)"
"node1"  "4/1.2/2.8"   "0/0/0"       "7.76/5.79/1.97"  "47.47/46.47/1"

ACTIVE TOTAL:
"cpu(cores)"  "gpu"  "mem(GiB)"  "ephemeral(GiB)"  "beta1(GiB)"  "beta2(GiB)"  "beta3(GiB)"

PERSISTENT STORAGE:
"storage class"  "available space(GiB)"

PENDING TOTAL:
"cpu(cores)"  "gpu"  "mem(GiB)"  "ephemeral(GiB)"  "beta1(GiB)"  "beta2(GiB)"  "beta3(GiB)"
0.5           0      0.5         0.5               0             0             0
```

**Comment by alexx855** [comment]
@vigneshv-ocl 40 more AKT have been loaded and more will be after the unstaking unbonding period.

**Comment by vigneshv-ocl** [comment]
@alexx855 

I tried to deploy something but there is a problem with the ingress
<img width="294" alt="image" src="https://github.com/user-attachments/assets/602f2672-c34a-4fd2-afcc-c9e550b1132f">

could you please try following this one
https://akash.network/docs/providers/build-a-cloud-provider/tls-certs-for-akash-provider/

**Comment by alexx855** [comment]
Hi @vigneshv-ocl, the problem has been resolved! thanks for noticing it.

![image](https://github.com/user-attachments/assets/e7818174-3d2d-43d9-9a3f-eb14bcb8114a)

**Comment by vigneshv-ocl** [comment]
@alexx855 welcome to Akash!!. your provider is audited

```
provider-services query audit get akash196z5qcz3m5suaymz653hcjzlwe5zhq25vnhj0f
pagination: null
providers:
- attributes:
  - key: arch
    value: amd64
  - key: host
    value: akash
  - key: organization
    value: Alex Pedersen
  - key: tier
    value: community
  auditor: akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
  owner: akash196z5qcz3m5suaymz653hcjzlwe5zhq25vnhj0f
```

you can find it here as well 👇

<img width="1196" alt="image" src="https://github.com/user-attachments/assets/0fe67d1a-ca76-4715-b3e2-e169923bb8cb">
