### ISSUE TITLE
[Provider Audit] provider.ak1.auxilio.ai

### ISSUE THREAD

**Issue by adrianfako** [akash-network/community#867]
### Resolved 
 
- Our AK1 provider has community provider attributes and contact details provider.ak1.auxilio.ai
- Provider IP resolves correctly
- Tetris works https://ko80es54el9o7a24rctd1f3os8.ingress.ak1.auxilio.ai/
- We have a few jobs already    
- We are using a firewall, ports are open and tested with tetris and comfyui

### Issues

- Even though the nodes are labeled and we can see the GPUs in the node description, we cannot bid on GPU jobs

```
D[2025-04-09|11:00:04.867] reservation requested. order=akash1jx5gztvud7tcdq6pfhz842xgjp9m0e3ufkd6pl/21005604/1/1, resources=[{"resource":{"id":1,"cpu":{"units":{"val":"6000"}},"memory":{"size":{"val":"37580963840"}},"storage":[{"name":"default","size":{"val":"53687091200"}}],"gpu":{"units":{"val":"1"},"attributes":[{"key":"vendor/nvidia/model/*","value":"true"}]},"endpoints":[{"kind":1,"sequence_number":0}]},"count":1,"price":{"denom":"uakt","amount":"10000.000000000000000000"}}] module=provider-cluster cmp=provider cmp=service cmp=inventory-service
I[2025-04-09|11:00:04.867] insufficient capacity for reservation        module=provider-cluster cmp=provider cmp=service cmp=inventory-service order=akash1jx5gztvud7tcdq6pfhz842xgjp9m0e3ufkd6pl/21005604/1/1
E[2025-04-09|11:00:04.867] reserving resources                          module=bidengine-order cmp=provider order=akash1jx5gztvud7tcdq6pfhz842xgjp9m0e3ufkd6pl/21005604/1/1 err="insufficient capacity"
I[2025-04-09|11:00:04.867] shutting down
```

Seems related to this one https://github.com/akash-network/support/issues/106

**Comment by shimpa1** [comment]
hi @adrianfako 

This is the status of the audit process:
Provider address: akash1mv7r6vfwjjdxhc72fh595evhhzft76e802k3wd
Provider URI: provider.ak1.auxilio.ai
Provider URI name resolution works? yes
Ingress URI name resolution works? yes
Provider status endpoint works? yes
Provider grpc status endpoint works? yes
Provider responding to orders? yes
Deployment works? yes
NodePort works? yes
Network functional? yes
Attributes OK? yes
GPU works?: no
Persistent Storage works: yes

Your provider is not placing bids on GPU orders.

Please try to deploy something on your own provider using a separate wallet and watch the provider pod logs for clues as to why it's happening.

There's also one huge limiting factor: There's only 60GB of ephemeral storage available on GPU nodes. As you probably know, AI workloads require a lot of storage. I strongly suggest at least 2TB of ephemeral storage per GPU node. This is not mandatory, the provider can pass the audit without it but will become an issue for you because your provider will most probably not receive any leases.

If you need assistance please reach out on Discord.

thanks,

Shimpa

**Comment by adrianfako** [comment]
Hi Shimpa, I have updated the nodes with proper latest drivers, tetris and comfyui now both work well. I have added more storage for the GPU nodes. Will keep and eye on the leases and add more resources as necessary.

Our second provider ak2.auxilio.ai is mirroring this one, maybe you can have a look there too. 

Thanks for the help!

Adrian

**Comment by vigneshv-ocl** [comment]
@adrianfako  welcome to Akash!!. your provider is audited

```
 provider-services query audit get akash1mv7r6vfwjjdxhc72fh595evhhzft76e802k3wd
pagination: null
providers:
- attributes:
  - key: capabilities/cpu
    value: intel
  - key: capabilities/cpu/arch
    value: x86-64
  - key: capabilities/cpu/model
    value: Xeon Gold 6248R 3.0 GHz
  - key: capabilities/gpu
    value: nvidia
  - key: capabilities/gpu/vendor/nvidia/model/rtxa6000
    value: "true"
  - key: capabilities/gpu/vendor/nvidia/model/rtxa6000/interface/pcie
    value: "true"
  - key: capabilities/gpu/vendor/nvidia/model/rtxa6000/ram/48Gi
    value: "true"
  - key: capabilities/gpu/vendor/nvidia/model/rtxa6000/ram/48Gi/interface/pcie
    value: "true"
  - key: capabilities/memory
    value: ddr4ecc
  - key: capabilities/storage
    value: ssd
  - key: capabilities/storage/0/class
    value: default
  - key: capabilities/storage/0/persistent
    value: "false"
  - key: capabilities/storage/1/class
    value: beta2
  - key: capabilities/storage/1/persistent
    value: "true"
  - key: capabilities/storage/2/class
    value: ram
  - key: capabilities/storage/2/persistent
    value: "false"
  - key: certifications
    value: ISO 9001:2020, ISO 27001:2024
  - key: country
    value: RO
  - key: email
    value: ak1@auxilio.ai
  - key: hardware-gpu
    value: Nvidia
  - key: hardware-gpu-model
    value: a6000
  - key: host
    value: akash
  - key: location-region
    value: eu-southeast
  - key: network-provider
    value: RCS-RDS
  - key: network-speed-down
    value: "5000"
  - key: network-speed-up
    value: "5000"
  - key: organization
    value: Auxilio AI
  - key: tier
    value: community
  auditor: akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63
  owner: akash1mv7r6vfwjjdxhc72fh595evhhzft76e802k3wd
```
you can find it here as well 👇

<img width="1184" alt="Image" src="https://github.com/user-attachments/assets/5920b92a-ff05-47c4-b0b6-bd356ec4e629" />
