### ISSUE TITLE
[Provider Audit] provider.akash.rhonet.net

### ISSUE THREAD

**Issue by rosswell98** [akash-network/community#911]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):
```
attributes:
  - key: host
    value: akash
  - key: tier
    value: community
  - key: organization
    value: RHONET
  - key: location-region
    value: eu-fr-paris
  - key: country
    value: FR
  - key: city
    value: Paris
  - key: location-type
    value: datacenter
  - key: hosting-provider
    value: RHONET
  - key: hardware-cpu
    value: intel
  - key: hardware-cpu-arch
    value: x86-64
  - key: network-speed-up
    value: "10000"
  - key: network-speed-down
    value: "10000"
  - key: hardware-disk
    value: ssd
  - key: website
    value: www.rhonet.eu
  - key: email
    value: noc@rhonet.eu
```

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
$ host provider.akash.rhonet.net
provider.akash.rhonet.net has address 156.229.230.227
```

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
```
Ports opened :
- TCP/22
- TCP/80
- TCP/443
- TCP/8443
- TCP/8444
- TCP/30000-32676

Dedicated IP Address : 156.229.230.227/32
Dedicated VLAN for Control Planes & Worker Nodes
```   

Thank you!
