### ISSUE TITLE
[Provider Audit] provider.choisyfoxandfamily.ovh

### ISSUE THREAD

**Issue by powertim** [akash-network/community#917]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
attributes:
  - key: host
    value: akash
  - key: tier
    value: community
  - key: organization
    value: CSY Foxes Hosting
  - key: country
    value: FR
  - key: location-region
    value: AURA
  - key: hardware-cpu
    value: intel
  - key: hardware-cpu-arch
    value: x86-64
  - key: hardware-disk
    value: ssd
  - key: feat-persistent-storage-type
    value: ssd
  - key: timezone
    value: europe/paris
  - key: email
    value: admin@choisyfoxandfamily.ovh
  - key: city
    value: Annecy
```

[Ref documentation:](https://akash.network/docs/providers/audited-attributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host provider.choisyfoxandfamily.ovh
provider.choisyfoxandfamily.ovh has address 109.190.132.189
host *.ingress.choisyfoxandfamily.ovh
*.ingress.choisyfoxandfamily.ovh has address 109.190.132.189
```

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.
   
Network isolation and configuration done.

## Leave contact information (optional)
email: admin@choisyfoxandfamily.ovh

Thanks for your help !
