### ISSUE TITLE
[Provider Audit] provider.rtgroup.com

### ISSUE THREAD

**Issue by j3rm** [akash-network/community#938]
### 1. Make sure your provider has community provider attributes and your contact details (email, website):

```
attributes:
- key: host
  value: akash
- key: tier
  value: community
- key: organization
  value: Remote Tech Group
- key: country
  value: US
- key: network-speed-up
  value: "1000"
- key: network-speed-down
  value: "1000"
- key: network-provider
  value: cogent
- key: location-region
  value: us-central
- key: location-type
  value: datacenter
- key: hardware-cpu-arch
  value: x86-64
- key: hardware-cpu
  value: amd
- key: hardware-memory
  value: ddr4ecc
- key: timezone
  value: CST
- key: website
  value: www.rtgroup.com
- key: city
  value: Dallas
- key: hardware-disk
  value: hdd, ssd
- key: feat-persistent-storage
  value: "true"
- key: feat-persistent-storage-type
  value: hdd,ssd
- key: feat-endpoint-ip
  value: "false"

```

[Ref documentation:](https://akash.network/docs/providers/audited-attributes/#attribute-auditors).

### 2. Make sure your provider *.ingress resolves to your provider IP (ideally worker node IP)
```
host provider.rtgroup.com
provider.rtgroup.com has address 39.96.202.140
host *.ingress.rtgroup.com
*.ingress.rtgroup.com has address 39.96.202.140
```

### 3. Please make sure your Akash provider doesn't block any Akash specific ports.

Network isolation and configuration done.

## Leave contact information (optional)
1. Name : Jeremy Wesley
2. Discord handle origJ3rm
3. Contact email address Jwesley@rtgroup.com
